### PR TITLE
Added a wizard for access entities

### PR DESCRIPTION
**Pull request by annndrey**
Second try, wrong code removed, sorry

### CODE REVIEW

**Comment by unikmhz** [comment]
In addition to all these, please consider fixing formatting (trailing commas, extra line breaks etc.)

**Comment by annndrey** [comment]
Ok, I can close this pull request and try to fix all the defects. After they are fixed, I'll make another pullrequest.

**Comment by unikmhz** [comment]
You know you can push future changes to this branch instead? Anyway, do what is more comfortable for you.

**Comment by annndrey** [comment]
Ok, it would be better, you're right

**Comment by unikmhz** [comment]
Hey @annndrey, I just refactored the whole wizard customization thing. Your code still got merged, but you might be interested in commits 1511ec244d2feb79c63cfe1db514b08531bac4b6 and ba36f224b423073b0b71bda4fd72e2d00c2bbc22

**Pull request merged**
